name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
        python-version: ["3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('docs/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade --upgrade-strategy eager pip
          pip install -r requirements.txt

      - name: Test with unittest
        env:
          HED_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m unittest
